version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "This is the build job"
    notify:
      docker:
        - image: cimg/base:current
      steps:
        - slack/notify:
            custom: |
              {
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "plain_text",
                        "text": "*This is a text notification*",
                        "emoji": true
                      }
                    ]
                  }
                ]
              }
            event: always
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "This is the test job"
workflows:
  build_and_test:
    jobs:
      - build
      - test
    send-notification:
      jobs:
        - notify